name: emp_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9
  flutter_secure_storage: ^9.2.2
  device_preview: ^1.2.0
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1
  flutter_local_notifications: ^17.2.1
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  persistent_bottom_nav_bar: ^6.2.1
  dio: ^5.5.0+1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  stepper_list_view: ^0.0.2
  anim_search_bar: ^2.0.3
  flutter_slidable: ^3.1.2
  universal_platform: ^1.0.0+1
  open_filex: ^4.7.0
  device_info_plus: ^11.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/venus_profile.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/image/svg/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
